const translations={es:{
"nav.story":"Historia","nav.menu":"Carta","nav.gallery":"Galería","nav.visit":"Visítanos","nav.reserve":"Reservar",
"hero.eyebrow":"Cocina italiana de autor · desde 1918","hero.title":"Italia, servida<br><em>con alma.</em>","hero.copy":"Una mesa en Palma, una historia que empezó en Pescara y platos preparados al momento con producto fresco.","hero.reserve":"Reservar mesa","hero.menu":"Descubrir la carta","hero.today":"Hoy","hero.location":"En el corazón de Palma",
"hours.short":"13:00 — 22:00","facts.years":"años de tradición","facts.since":"origen en Pescara","facts.fresh":"hecho al momento",
"story.eyebrow":"La historia detrás de la mesa","story.title":"Una familia que cocina<br>desde hace cuatro generaciones.","story.lead":"El legado gastronómico de la familia Caporale comenzó en 1918 en Pescara, Abruzzo. Michele continuó esa tradición y la llevó a Mallorca en 1998.","story.body":"Hoy, La Bottega mantiene la misma idea sencilla: producto de calidad, cocina hecha al momento y una hospitalidad cercana, como si cada cliente entrara en casa.","story.quote":"“Bienvenido a casa.”","story.badge":"Tradición que sigue viva",
"featured.eyebrow":"Elige con los ojos","featured.title":"Algunos platos que merecen<br>ser el motivo de tu visita.","featured.casserole":"A la cazuela","featured.lobster":"Bogavante, frutos del mar y el sabor intenso de la cazuela de barro.","featured.pasta":"Pasta bio","featured.sophia":"Gambas, setas, crema de tartufo blanco y parmesano.","featured.ritual":"El ritual","featured.parmesan":"Parmigiano Reggiano de 30 meses, pimienta negra y aceite de trufa.","featured.dessert":"Postre casero","featured.panna":"Flan italiano de nata y vainilla con frutos del bosque.","featured.swipe":"Desliza para descubrir →",
"menu.eyebrow":"Carta 2026","menu.title":"La carta, hecha para elegir<br>sin prisas.","menu.note":"Todos los precios incluyen IVA. Los platos de cazuela son para mínimo 2 personas. S.P.M. = según precio de mercado.","menu.search":"Buscar un plato","menu.allergens":"¿Alergias o intolerancias? Pregunta a nuestro equipo antes de pedir.","menu.all":"Todo","menu.starters":"Entrantes","menu.casserole":"A la cazuela","menu.pasta":"Pasta","menu.meatfish":"Carnes & pescados","menu.desserts":"Postres","menu.wines":"Bodega",
"gallery.eyebrow":"La experiencia","gallery.title":"Un rincón de Italia<br>en Santa Catalina.",
"visit.eyebrow":"Ven a vernos","visit.title":"Tu mesa está en<br>Palma.","visit.directions":"Cómo llegar","hours.title":"Horario de cocina","hours.monTue":"Lunes — Martes","hours.wed":"Miércoles","hours.closed":"Cerrado","hours.thuSat":"Jueves — Sábado","hours.sun":"Domingo","hours.call":"Reservas telefónicas de 11:30 a 22:00.",
"mobile.menu":"Carta","mobile.reserve":"Reservar","mobile.call":"Llamar",
"reserve.eyebrow":"Reserva fácil","reserve.title":"Prepara tu reserva<br>en segundos.","reserve.copy":"Completa los datos y te llevamos a WhatsApp con el mensaje preparado. El restaurante confirmará disponibilidad.","reserve.name":"Nombre","reserve.people":"Personas","reserve.date":"Fecha","reserve.time":"Hora","reserve.note":"Nota opcional","reserve.notePlaceholder":"Alergias, terraza, celebración...","reserve.whatsapp":"Continuar por WhatsApp","reserve.phone":"O llamar al +34 971 454 892","reserve.message":"Hola, me gustaría solicitar una reserva en La Bottega di Michele."},
en:{
"nav.story":"Story","nav.menu":"Menu","nav.gallery":"Gallery","nav.visit":"Visit","nav.reserve":"Book",
"hero.eyebrow":"Signature Italian cuisine · since 1918","hero.title":"Italy, served<br><em>with soul.</em>","hero.copy":"A table in Palma, a story that began in Pescara, and dishes made to order with fresh ingredients.","hero.reserve":"Book a table","hero.menu":"Explore the menu","hero.today":"Today","hero.location":"In the heart of Palma",
"hours.short":"13:00 — 22:00","facts.years":"years of tradition","facts.since":"born in Pescara","facts.fresh":"made to order",
"story.eyebrow":"The story behind the table","story.title":"A family that has cooked<br>for four generations.","story.lead":"The Caporale family's culinary legacy began in 1918 in Pescara, Abruzzo. Michele continued that tradition and brought it to Mallorca in 1998.","story.body":"Today, La Bottega keeps the same simple idea: quality ingredients, food prepared to order and warm hospitality, as if every guest were coming home.","story.quote":"“Welcome home.”","story.badge":"A living tradition",
"featured.eyebrow":"Choose with your eyes","featured.title":"A few dishes worth making<br>the journey for.","featured.casserole":"Terracotta pot","featured.lobster":"Lobster, seafood and the deep flavour of a traditional terracotta pot.","featured.pasta":"Organic pasta","featured.sophia":"Prawns, mushrooms, white truffle cream and Parmesan.","featured.ritual":"The ritual","featured.parmesan":"30-month Parmigiano Reggiano, black pepper and truffle oil.","featured.dessert":"Homemade dessert","featured.panna":"Italian cream and vanilla flan with forest berries.","featured.swipe":"Swipe to discover →",
"menu.eyebrow":"2026 Menu","menu.title":"A menu made for choosing<br>without rushing.","menu.note":"All prices include VAT. Terracotta-pot dishes are for a minimum of 2 people. M.P. = market price.","menu.search":"Search the menu","menu.all":"All","menu.starters":"Starters","menu.casserole":"Terracotta pot","menu.pasta":"Pasta","menu.meatfish":"Meat & fish","menu.desserts":"Desserts","menu.wines":"Wine cellar","menu.allergens":"Allergies or intolerances? Please ask our team before ordering.",
"gallery.eyebrow":"The experience","gallery.title":"A corner of Italy<br>in Santa Catalina.",
"visit.eyebrow":"Come and see us","visit.title":"Your table is in<br>Palma.","visit.directions":"Get directions","hours.title":"Kitchen hours","hours.monTue":"Monday — Tuesday","hours.wed":"Wednesday","hours.closed":"Closed","hours.thuSat":"Thursday — Saturday","hours.sun":"Sunday","hours.call":"Telephone reservations from 11:30 to 22:00.",
"mobile.menu":"Menu","mobile.reserve":"Book","mobile.call":"Call",
"reserve.eyebrow":"Easy booking","reserve.title":"Prepare your booking<br>in seconds.","reserve.copy":"Fill in the details and we'll open WhatsApp with your message ready. The restaurant will confirm availability.","reserve.name":"Name","reserve.people":"Guests","reserve.date":"Date","reserve.time":"Time","reserve.note":"Optional note","reserve.notePlaceholder":"Allergies, terrace, celebration...","reserve.whatsapp":"Continue on WhatsApp","reserve.phone":"Or call +34 971 454 892","reserve.message":"Hello, I would like to request a reservation at La Bottega di Michele."}
};

const menuData=[
{cat:"starters",es:"Ensalada caprese con mozzarella de búfala",en:"Caprese salad with buffalo mozzarella",price:"16€",descEs:"Tomate, mozzarella de búfala y albahaca.",descEn:"Tomato, buffalo mozzarella and basil."},
{cat:"starters",es:"Ensalada de queso de cabra templada",en:"Warm goat's cheese salad",price:"16€",descEs:"Con confitura de tomate.",descEn:"With tomato preserve."},
{cat:"starters",es:"Porchetta deshuesada all'Abruzzese",en:"Boneless Porchetta all'Abruzzese",price:"18€",descEs:"Con rúcula, parmesano, albahaca y aceite de trufa.",descEn:"With rocket, Parmesan, basil and truffle oil."},
{cat:"starters",es:"Ensalada de foie",en:"Foie salad",price:"22€",descEs:"Con confitura de frutos del bosque, pasas y piñones.",descEn:"With forest berry preserve, raisins and pine nuts."},
{cat:"starters",es:"Ensalada tropical",en:"Tropical salad",price:"16€",descEs:"Piña, pera, uva, tomate cherry, parmesano y reducción balsámica.",descEn:"Pineapple, pear, grapes, cherry tomato, Parmesan and balsamic reduction."},
{cat:"starters",es:"Anchoas del Cantábrico",en:"Cantabrian anchovies",price:"18€",descEs:"Con pimientos del Piquillo.",descEn:"With Piquillo peppers."},
{cat:"starters",es:"Ensalada mixta mediterránea",en:"Mediterranean mixed salad",price:"9€",descEs:"Fresca y sencilla.",descEn:"Fresh and simple."},
{cat:"starters",es:"Ensalada con ventresca de atún",en:"Tuna belly salad",price:"18€",descEs:"Selección mediterránea.",descEn:"Mediterranean selection."},
{cat:"starters",es:"Ensalada templada al gorgonzola",en:"Warm Gorgonzola salad",price:"16€",descEs:"Con espárragos verdes y nueces.",descEn:"With green asparagus and walnuts."},
{cat:"starters",es:"Carpaccio de ternera",en:"Beef carpaccio",price:"18€",descEs:"Con rúcula, manzana verde y parmesano.",descEn:"With rocket, green apple and Parmesan."},
{cat:"starters",es:"Carpaccio de atún marinado",en:"Marinated tuna carpaccio",price:"18€",descEs:"Con soja y tomate seco.",descEn:"With soy and sun-dried tomato."},
{cat:"starters",es:"Vitello Tonnato",en:"Vitello Tonnato",price:"16€",descEs:"Lomo de cerdo al horno con atún, alcaparras y mayonesa.",descEn:"Roast pork loin with tuna, capers and mayonnaise."},
{cat:"starters",es:"Antipasto a la italiana",en:"Italian antipasto",price:"24€",descEs:"Salami, prosciutto y mozzarella.",descEn:"Salami, prosciutto and mozzarella."},
{cat:"starters",es:"Gambas al ajillo",en:"Garlic prawns",price:"21€",descEs:"Clásico de la casa.",descEn:"A house classic."},
{cat:"starters",es:"Gambas con setas del abogado",en:"Prawns with seasonal mushrooms",price:"22€",descEs:"Preparación de la casa.",descEn:"House preparation."},
{cat:"starters",es:"Revuelto de mozzarella fresca",en:"Fresh mozzarella scramble",price:"18€",descEs:"Con huevos ecológicos y aceite de trufa.",descEn:"With organic eggs and truffle oil."},
{cat:"casserole",es:"Spaghetti con bogavante",en:"Spaghetti with lobster",price:"S.P.M.",descEs:"En cazuela de barro, con frutti di mare. Mín. 2 pers.",descEn:"Terracotta pot with seafood. Min. 2 guests."},
{cat:"casserole",es:"Spaghetti con gambas",en:"Spaghetti with prawns",price:"22€ p.p.",descEs:"Tomate de colina, ajo, perejil y coñac. Mín. 2 pers.",descEn:"Hill tomatoes, garlic, parsley and cognac. Min. 2 guests."},
{cat:"casserole",es:"Linguini con ventresca de atún",en:"Linguine with tuna belly",price:"19€ p.p.",descEs:"Ajo, perejil y tomates de colina. Mín. 2 pers.",descEn:"Garlic, parsley and hill tomatoes. Min. 2 guests."},
{cat:"casserole",es:"Spaghetti Vongole",en:"Spaghetti Vongole",price:"25€ p.p.",descEs:"Almejas, ajo, perejil y vino blanco. Mín. 2 pers.",descEn:"Clams, garlic, parsley and white wine. Min. 2 guests."},
{cat:"casserole",es:"Spaghetti all'Arrabbiata",en:"Spaghetti all'Arrabbiata",price:"16€ p.p.",descEs:"Tomate, olivas negras, cebolla, albahaca, guindilla y parmesano.",descEn:"Tomato, black olives, onion, basil, chilli and Parmesan."},
{cat:"casserole",es:"Spaghetti alla Americana",en:"Spaghetti alla Americana",price:"18€ p.p.",descEs:"Guanciale, tomate y parmesano. Mín. 2 pers.",descEn:"Guanciale, tomato and Parmesan. Min. 2 guests."},
{cat:"pasta",es:"Pappardelle alla Sophia Loren",en:"Pappardelle alla Sophia Loren",price:"22€",descEs:"Gambas, setas, crema de tartufo blanco y parmesano.",descEn:"Prawns, mushrooms, white truffle cream and Parmesan."},
{cat:"pasta",es:"Spaghetti aglio, olio e peperoncino",en:"Spaghetti aglio, olio e peperoncino",price:"16€",descEs:"Ajo, guindilla y parmesano.",descEn:"Garlic, chilli and Parmesan."},
{cat:"pasta",es:"Spaghetti alla Bolognese",en:"Spaghetti alla Bolognese",price:"16€",descEs:"Ragú de ternera y parmesano.",descEn:"Beef ragù and Parmesan."},
{cat:"pasta",es:"Tagliatelle con tomate, burrata y pesto",en:"Tagliatelle with tomato, burrata and pesto",price:"18€",descEs:"Tomate, burrata cremosa y pesto.",descEn:"Tomato, creamy burrata and pesto."},
{cat:"pasta",es:"Pappardelle con ragú de ciervo",en:"Pappardelle with venison ragù",price:"20€",descEs:"Con setas y parmesano.",descEn:"With mushrooms and Parmesan."},
{cat:"pasta",es:"Ravioli rellenos de trufa",en:"Truffle-filled ravioli",price:"22€",descEs:"Crema de setas y parmesano.",descEn:"Mushroom cream and Parmesan."},
{cat:"pasta",es:"Ravioli rellenos de foie",en:"Foie-filled ravioli",price:"25€",descEs:"Salsa de setas, trufa y parmesano.",descEn:"Mushroom sauce, truffle and Parmesan."},
{cat:"pasta",es:"Ravioli rellenos de calabaza",en:"Pumpkin-filled ravioli",price:"16€",descEs:"Con crema de queso.",descEn:"With cheese cream."},
{cat:"pasta",es:"Tagliatelle en rueda de Parmigiano Reggiano",en:"Tagliatelle in a Parmigiano Reggiano wheel",price:"22€",descEs:"Parmigiano de 30 meses, pimienta negra y aceite de trufa.",descEn:"30-month Parmigiano, black pepper and truffle oil."},
{cat:"meatfish",es:"Foie fresco a la plancha",en:"Grilled fresh foie gras",price:"32€",descEs:"Manzanas caramelizadas al Pedro Ximénez.",descEn:"Caramelised apples with Pedro Ximénez."},
{cat:"meatfish",es:"Pollo con risotto",en:"Chicken with risotto",price:"21€",descEs:"Setas, parmesano y aceite de trufa.",descEn:"Mushrooms, Parmesan and truffle oil."},
{cat:"meatfish",es:"Tagliata alla Fiorentina de entrecot",en:"Entrecote Tagliata alla Fiorentina",price:"28€",descEs:"Entrecot fileteado con rúcula y parmesano.",descEn:"Sliced entrecote with rocket and Parmesan."},
{cat:"meatfish",es:"Entrecot a la plancha",en:"Grilled entrecote",price:"28€",descEs:"Fileteado con patatas a la provenzal.",descEn:"Sliced with Provençal potatoes."},
{cat:"meatfish",es:"Paletilla de cordero al horno",en:"Oven-baked lamb shoulder",price:"32€",descEs:"Con patatas.",descEn:"With potatoes."},
{cat:"meatfish",es:"Lubina a la Siciliana al horno",en:"Sicilian-style baked sea bass",price:"S.P.M.",descEs:"Verdura, patata parmentine, olivas negras y vino blanco. Mín. 2 pers.",descEn:"Vegetables, parmentine potatoes, black olives and white wine. Min. 2 guests."},
{cat:"meatfish",es:"Bacalao a la Terramana",en:"Cod Terramana style",price:"32€",descEs:"Con salsa marinera y patata.",descEn:"With seafood sauce and potato."},
{cat:"meatfish",es:"Pescado de mercado",en:"Market fish",price:"S.P.M.",descEs:"Según disponibilidad del día.",descEn:"According to today's catch."},
{cat:"desserts",es:"Tiramisú",en:"Tiramisu",price:"8€",descEs:"Clásico italiano de la casa.",descEn:"House Italian classic."},
{cat:"desserts",es:"Tarta de queso con frutos del bosque",en:"Cheesecake with forest berries",price:"7,50€",descEs:"Cremosa y casera.",descEn:"Creamy and homemade."},
{cat:"desserts",es:"Mousse de chocolate blanco",en:"White chocolate mousse",price:"7,50€",descEs:"Suave y ligera.",descEn:"Smooth and light."},
{cat:"desserts",es:"Mousse de chocolate negro",en:"Dark chocolate mousse",price:"7,50€",descEs:"Intensa y cremosa.",descEn:"Rich and creamy."},
{cat:"desserts",es:"Panna Cotta",en:"Panna Cotta",price:"7,50€",descEs:"Flan italiano de nata y vainilla con frutos del bosque.",descEn:"Italian cream and vanilla flan with forest berries."},
{cat:"desserts",es:"Sorbete de limón",en:"Lemon sorbet",price:"7,50€",descEs:"Fresco y cítrico.",descEn:"Fresh and citrusy."},
{cat:"desserts",es:"Sorbete de mango",en:"Mango sorbet",price:"7,50€",descEs:"Frutal y refrescante.",descEn:"Fruity and refreshing."},
{cat:"desserts",es:"Affogato",en:"Affogato",price:"8€",descEs:"Helado de vainilla con café.",descEn:"Vanilla ice cream with coffee."},
{cat:"desserts",es:"Banoffee",en:"Banoffee",price:"7,50€",descEs:"Postre cremoso de plátano y caramelo.",descEn:"Creamy banana and caramel dessert."},
{cat:"wines",es:"Marqués de Murrieta Reserva",en:"Marqués de Murrieta Reserva",price:"39€",descEs:"Tempranillo, Garnacha, Mazuelo · D.O. Rioja.",descEn:"Tempranillo, Garnacha, Mazuelo · D.O. Rioja."},
{cat:"wines",es:"Pedra de Binissalem Eco",en:"Pedra de Binissalem Eco",price:"22€",descEs:"Manto Negro y Cabernet · D.O. Binissalem.",descEn:"Manto Negro and Cabernet · D.O. Binissalem."},
{cat:"wines",es:"Sassicaia 2015",en:"Sassicaia 2015",price:"S.P.M.",descEs:"Sauvignon y Cabernet Franc · D.O. Toscana.",descEn:"Sauvignon and Cabernet Franc · D.O. Toscana."}
];

let lang="es",activeCat="all",searchTerm="";
const categories=["all","starters","casserole","pasta","meatfish","desserts","wines"];
const t=k=>translations[lang][k]||k;
function updateTodayHours(){const d=new Date().getDay();const el=document.getElementById("todayHours");if(!el)return;if(d===3)el.textContent=lang==="es"?"Cerrado":"Closed";else if(d===0)el.textContent="13:00 — 16:00";else el.textContent="13:00 — 22:00";}
function applyTranslations(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>el.innerHTML=t(el.dataset.i18n));document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.getElementById("langSwitch").textContent=lang==="es"?"EN":"ES";updateTodayHours();renderTabs();renderMenu();}
function renderTabs(){document.getElementById("categoryTabs").innerHTML=categories.map(c=>`<button type="button" data-cat="${c}" class="${activeCat===c?"active":""}">${t("menu."+c)}</button>`).join("");document.querySelectorAll("#categoryTabs button").forEach(b=>b.addEventListener("click",()=>{activeCat=b.dataset.cat;renderTabs();renderMenu();}));}
function renderMenu(){const q=searchTerm.trim().toLowerCase();const filtered=menuData.filter(i=>(activeCat==="all"||i.cat===activeCat)&&(!q||`${i[lang]} ${lang==="es"?i.descEs:i.descEn}`.toLowerCase().includes(q)));const groupCats=activeCat==="all"?categories.slice(1):[activeCat];let html="";groupCats.forEach(cat=>{const items=filtered.filter(i=>i.cat===cat);if(!items.length)return;html+=`<div class="menu-category"><h3 class="menu-category-title">${t("menu."+cat)}</h3>${items.map(i=>`<article class="menu-item"><div><h4>${i[lang]}</h4><p>${lang==="es"?i.descEs:i.descEn}</p></div><span class="menu-price">${i.price}</span></article>`).join("")}</div>`});document.getElementById("menuList").innerHTML=html||`<div class="menu-empty">${lang==="es"?"No encontramos ese plato.":"No dishes found."}</div>`;}

document.getElementById("langSwitch").addEventListener("click",()=>{lang=lang==="es"?"en":"es";applyTranslations();});
document.getElementById("menuSearch").addEventListener("input",e=>{searchTerm=e.target.value;renderMenu();});
const toggle=document.getElementById("menuToggle"),mobileNav=document.getElementById("mobileNav");toggle.addEventListener("click",()=>{const open=mobileNav.classList.toggle("open");toggle.setAttribute("aria-expanded",open);mobileNav.setAttribute("aria-hidden",!open);});mobileNav.querySelectorAll("a,button").forEach(el=>el.addEventListener("click",()=>{mobileNav.classList.remove("open");toggle.setAttribute("aria-expanded","false");mobileNav.setAttribute("aria-hidden","true");}));

const modal=document.getElementById("reservationModal");function openModal(){modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow="";}document.querySelectorAll(".reserve-trigger").forEach(b=>b.addEventListener("click",openModal));document.querySelectorAll("[data-close-modal]").forEach(b=>b.addEventListener("click",closeModal));document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeLightbox();}});
const dateInput=document.getElementById("resDate");dateInput.min=new Date().toISOString().split("T")[0];document.getElementById("reservationForm").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("resName").value,people=document.getElementById("resPeople").value,date=document.getElementById("resDate").value,time=document.getElementById("resTime").value,note=document.getElementById("resNote").value;const msg=lang==="es"?`${t("reserve.message")}\n\nNombre: ${name}\nPersonas: ${people}\nFecha: ${date}\nHora: ${time}${note?`\nNota: ${note}`:""}`:`${t("reserve.message")}\n\nName: ${name}\nGuests: ${people}\nDate: ${date}\nTime: ${time}${note?`\nNote: ${note}`:""}`;window.open(`https://wa.me/34971454892?text=${encodeURIComponent(msg)}`,"_blank");});

const lightbox=document.getElementById("lightbox"),lightboxImg=document.getElementById("lightboxImg");function closeLightbox(){lightbox.classList.remove("open");lightbox.setAttribute("aria-hidden","true");}document.querySelectorAll(".gallery-item").forEach(b=>b.addEventListener("click",()=>{lightboxImg.src=b.dataset.img;lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false");}));document.getElementById("lightboxClose").addEventListener("click",closeLightbox);lightbox.addEventListener("click",e=>{if(e.target===lightbox)closeLightbox();});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
applyTranslations();
